### ISSUE TITLE
is there any sample?

### ISSUE THREAD

**Issue by drony** [rdlaitila/Orleans.EntityFrameworkCore#1]
is there any sample?

**Comment by rdlaitila** [comment]
@drony 

Thanks for your interest! No sample yet. This project is highly experimental and is being improved as needed for another one of my projects. 

I have commited the latest changes to the repository and updated the readme to include a configuration sample. In addition I have uploaded a new package to nuget (v0.1.1) 

There are some tests available for review here https://github.com/rdlaitila/Orleans.EntityFrameworkCore/tree/master/src/Orleans.EntityFrameworkCore.Tests that detail some of the configuration needed for the various orleans providers.

Thanks!
